version: '3'
services:
  db-postgres:
    image: postgres:11.3
    container_name: postgres_container
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=digitaldocs
      - POSTGRES_USER=digitaldocs
      - POSTGRES_PASSWORD=digitaldocs
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: